#!/bin/bash
# Periscope - Network auditing tool
# Copyright (C) 2009 Harry Bock <harry@oshean.org>

# This file is part of Periscope.

# periscope is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# periscope is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with periscope; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

# Simple script wrapping rabins/rasplit for use with Periscope.
# Syntax:
#   racollector tinderbox.oshean.lan 1h "reports/hourly/h.%Y%m%d-%H"
#
# Called from Lisp using EXECUTE-COMMAND.
# To stop, simply raise SIGINT to this process.

rabins=$(which ${PREFIX}rabins)
rasplit=$(which ${PREFIX}rasplit)

error_message()
{
    [ -n "$1" ] && echo $1 >&2
}

usage()
{
    error_message "Usage: $0 argus-server time-period output-format"
    exit 2
}

if [ ! -x $rabins ] && [ ! -x $rasplit ]; then
    error_message "Error: rabins/rasplit not found. Please install argus-clients!"
    exit 3
fi

# Check arguments - none can be empty.
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then usage; fi

sighandler()
{
    # Find all child processes of this script ($$)...
    for pid in $(ps -ef | awk "\$3 == $$ { print \$2 }")
    do
	# ...and kill them dead.  Gracefully, of course :)
	kill -TERM $pid &> /dev/null
    done
    exit 0
}
# We only send SIGTERM from Periscope, but best be safe.
trap sighandler SIGINT SIGTERM SIGHUP

# Run rabins/rasplit pipe as a job - we need to do this so we will
# actually trap SIGTERM. If we don't, bash will wait until rabins/rasplit
# finish before invoking the trap handler.
$rabins -S $1 -M time $2 -B 20s -w - | $rasplit -M time $2 -w "$3" &

# Busy wait while rabins/rasplit run.  Sleep momentarily to yield the processor.
# This is a hack, I know.
# The handler may not be called immediately - it will be called in-between invocations
# of 'sleep 0.5' below... bash must wait until running child processes complete before
# handling any pending signals.  Which is why this hack is needed in the first place!
while [ 1 ]; do
    sleep 0.5
    # Check to see if the child processes exited; if so, abort with error code 4.
    if ! ps -p ${!} &> /dev/null; then
	exit 4;
    fi
done

exit 0
